<?php
/**
 * Gutenverse Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Hero', 'startupzy' ),
	'categories' => array( 'startupzy-gutenverse' ),
	'content'    => '
        <!-- wp:gutenverse/section {"width":"1170","elementId":"guten-4qr4Df","background":{"type":"default","image":{"Desktop":{"id":128,"image":"' . esc_url( STARTUPZY_URI ) . 'assets/img/action-african-american-african-descent-agreement-american-black-1448357-pxhere.com.webp"}},"position":{"Desktop":"center center","Tablet":"center center","Mobile":"center center"},"size":{"Desktop":"cover","Tablet":"cover"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"yposition":{"Tablet":{"point":"1","unit":"px"},"Mobile":{"point":"","unit":"px"}},"xposition":{"Tablet":{"unit":"vh","point":"0.1"},"Mobile":{"unit":"em","point":""}}},"backgroundOverlay":{"type":"default","color":{"r":1,"g":12,"b":28,"a":1},"gradientColor":[{"color":"rgba(85, 85, 85, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(7, 7, 7, 1)","active":true,"id":5,"offset":"0.078"}],"gradientType":"linear","gradientAngle":"180"},"opacity":"0.75","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"260","bottom":"300"}},"Tablet":{"unit":"px","dimension":{"top":"140","bottom":"200","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"140","bottom":"180"}}},"zIndex":{"Desktop":""},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
        <div class="section-wrapper" data-id="4qr4Df"><script>var top4qr4Df = {"Desktop":{"point":"0","unit":"px"}};var bottom4qr4Df = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-4qr4Df layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":80,"Mobile":null},"elementId":"guten-3vgI6y"} -->
        <div class="wp-block-gutenverse-column guten-element guten-column guten-3vgI6y"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3vgI6y"><script>var top3vgI6y = {"Desktop":{"point":"0","unit":"px"}};var bottom3vgI6y = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-q3mXI6","type":1,"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"size":{"Desktop":{"point":"60","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","font":{"label":"Helvetica","value":"Helvetica","type":"system"}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow"}} -->
        <h1 class="wp-block-gutenverse-heading guten-element guten-q3mXI6 animated guten-element-hide slow desktop-fadeInLeft">We Are A Startup Makes Everything Tech Based</h1>
        <!-- /wp:gutenverse/heading -->
        
        <!-- wp:gutenverse/text-editor {"elementId":"guten-kxbE7L","textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"180"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"slow"}} -->
        <div class="guten-element gutenverse-text-editor guten-kxbE7L animated guten-element-hide slow desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua nostrud exercitation</p>
        <!-- /wp:paragraph --></div></div>
        <!-- /wp:gutenverse/text-editor -->
        
        <!-- wp:gutenverse/button {"elementId":"guten-eMzUe0","content":"Get Started","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"r":30,"g":112,"b":234,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"0"}}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"13","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.15"}},"hoverTextColor":{"r":30,"g":112,"b":234,"a":1}} -->
        <div class="guten-element guten-button-wrapper guten-eMzUe0"><a class="guten-button animated guten-element-hide slow desktop-fadeInLeft guten-button-sm" href="#"><span>Get Started</span></a></div>
        <!-- /wp:gutenverse/button --></div></div></div>
        <!-- /wp:gutenverse/column -->
        
        <!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":20,"Mobile":null},"elementId":"guten-ejE6jy","margin":{"Mobile":[]},"padding":{"Mobile":[]},"hideMobile":true} -->
        <div class="wp-block-gutenverse-column guten-element guten-column guten-ejE6jy hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ejE6jy"><script>var topejE6jy = {"Desktop":{"point":"0","unit":"px"}};var bottomejE6jy = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"></div></div></div>
        <!-- /wp:gutenverse/column --></div></section></div>
        <!-- /wp:gutenverse/section -->',
);
