<?php
/**
 * Gutenverse FAQ content.
 */
return array(
	'title'      => __( 'Gutenverse FAQ', 'startupzy' ),
	'categories' => array( 'startupzy-gutenverse' ),
	'content'    => '
            <!-- wp:gutenverse/section {"width":"1170","elementId":"guten-AMGete","verticalAlign":"center","margin":{"Desktop":{},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"60"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80","left":"10","right":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}}} -->
            <div class="section-wrapper" data-id="AMGete"><script>var topAMGete = {"Desktop":{"point":"0","unit":"px"}};var bottomAMGete = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-AMGete layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":52,"Tablet":100},"elementId":"guten-TIR12Z","margin":{"Desktop":{"unit":"px","dimension":{"left":"","right":"60"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-TIR12Z"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="TIR12Z"><script>var topTIR12Z = {"Desktop":{"point":"0","unit":"px"}};var bottomTIR12Z = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-7otlnJ","color":{"r":30,"g":112,"b":234,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.15"},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"transform":"uppercase"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-7otlnJ animated guten-element-hide slow desktop-fadeInLeft">FAQ</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/heading {"elementId":"guten-2W1hqH","textAlign":{"Desktop":"left","Mobile":"left"},"color":{"r":7,"g":41,"b":90,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"spacing":{"Desktop":""},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}}}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-2W1hqH">Popular Question</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-bwmK4G","textColor":{"r":113,"g":124,"b":144,"a":1},"typography":{"size":{"Mobile":{"point":"14","unit":"px"},"Desktop":{"point":"16","unit":"px"}},"font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"300"},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"right":""}}}} -->
            <div class="guten-element gutenverse-text-editor guten-bwmK4G"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->
            
            <!-- wp:gutenverse/accordions {"elementId":"guten-8Gt8L1","iconClosed":"fas fa-chevron-down","iconPosition":"right","iconColor":{"r":30,"g":112,"b":234,"a":1},"iconActiveColor":{"r":255,"g":255,"b":255,"a":1},"titleBackgroundColor":{"r":255,"g":255,"b":255,"a":1},"titleTextColor":{"r":7,"g":41,"b":90,"a":1},"titleActiveColor":{"r":255,"g":255,"b":255,"a":1},"titleTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Mobile":{"unit":"em","point":"1.4"}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"30","bottom":"25","left":"30"}},"Mobile":[]},"contentBackgroundColor":{"r":255,"g":255,"b":255,"a":1},"contentTextColor":{"r":113,"g":124,"b":144,"a":1},"contentTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}},"accordionBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Mobile":[]},"all":{"type":"none"}},"titleBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"","bottom":"10","left":""}},"Mobile":[]},"all":{"type":"none"}},"contentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}},"Mobile":[]}},"background":{"type":"default","color":""},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"accordionBorderActive":{"radius":{"Desktop":[]},"all":{"type":"none"}},"accordionMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"30","top":"","right":"","left":""}},"Mobile":[]},"contentTextColorActive":{"r":113,"g":124,"b":144,"a":1},"contentBorderActive":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}}},"titleBackgroundActiveColor":{"r":30,"g":112,"b":234,"a":1},"titleBorderActive":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}}},"accordionBoxShadow":{"color":{"r":1,"g":1,"b":1,"a":0.08},"horizontal":"0","vertical":"3","blur":"15","spread":"0"},"accordionBoxShadowActive":{"color":{"r":160,"g":157,"b":157,"a":0.1},"horizontal":"0","vertical":"0","blur":"30","spread":"1"}} -->
            <div class="guten-element guten-accordions guten-8Gt8L1"><!-- wp:gutenverse/accordion {"elementId":"guten-mpgC1R","iconClosed":"fas fa-chevron-down","iconPosition":"right"} -->
            <div class="accordion-item"><div class="accordion-heading"><span class="accordion-text">Do I have to commit to a contract?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-minus"></i></span><span class="accordion-icon-closed"><i class="fas fa-chevron-down"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
            <!-- /wp:paragraph --></div></div></div>
            <!-- /wp:gutenverse/accordion -->
            
            <!-- wp:gutenverse/accordion {"elementId":"guten-My4NFQ","iconClosed":"fas fa-chevron-down","iconPosition":"right"} -->
            <div class="accordion-item"><div class="accordion-heading"><span class="accordion-text"><meta charset="utf-8">What Payment Methods Are Available?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-minus"></i></span><span class="accordion-icon-closed"><i class="fas fa-chevron-down"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
            <p><meta charset="utf-8">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
            <!-- /wp:paragraph --></div></div></div>
            <!-- /wp:gutenverse/accordion -->
            
            <!-- wp:gutenverse/accordion {"elementId":"guten-Kq0NFL","first":true,"iconClosed":"fas fa-chevron-down","iconPosition":"right"} -->
            <div class="accordion-item active"><div class="accordion-heading"><span class="accordion-text">Where Can I Find More Information?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-minus"></i></span><span class="accordion-icon-closed"><i class="fas fa-chevron-down"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
            <p><meta charset="utf-8">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
            <!-- /wp:paragraph --></div></div></div>
            <!-- /wp:gutenverse/accordion --></div>
            <!-- /wp:gutenverse/accordions --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":48,"Tablet":100,"Mobile":null},"elementId":"guten-150ahz","background":{"type":"default","image":{"Desktop":{"id":13,"image":"' . esc_url( STARTUPZY_URI ) . 'assets/img/action-american-asian-beverage-brainstorming-business-1449315-pxhere.com.webp"}},"size":{"Desktop":"cover"},"position":{"Desktop":"center center"},"xposition":{"Desktop":{"unit":"px","point":""}},"yposition":{"Desktop":{"unit":"px","point":""}},"repeat":{"Desktop":"no-repeat"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"50","left":"0"}}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"slow"}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-150ahz animated guten-element-hide slow desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="150ahz"><script>var top150ahz = {"Desktop":{"point":"0","unit":"px"}};var bottom150ahz = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-9e6amf","space":{"Desktop":{"point":"620","unit":"px"},"Mobile":{"point":"289","unit":"px"}}} -->
            <div class="guten-element guten-spacer guten-9e6amf"></div>
            <!-- /wp:gutenverse/spacer --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
