<?php
/**
 * Gutenverse Team content.
 */
return array(
	'title'      => __( 'Gutenverse Team', 'startupzy' ),
	'categories' => array( 'startupzy-gutenverse' ),
	'content'    => '
            <!-- wp:gutenverse/section {"elementId":"guten-N51LwF","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"20"}}}} -->
            <div class="section-wrapper" data-id="N51LwF"><script>var topN51LwF = {"Desktop":{"point":"0","unit":"px"}};var bottomN51LwF = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-N51LwF layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-9407cx","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-9407cx"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="9407cx"><script>var top9407cx = {"Desktop":{"point":"0","unit":"px"}};var bottom9407cx = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-3tPrxG","type":5,"textAlign":{"Desktop":"center"},"color":{"r":30,"g":112,"b":234,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.15"},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"transform":"uppercase"}} -->
            <h5 class="wp-block-gutenverse-heading guten-element guten-3tPrxG">Our Team</h5>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/heading {"elementId":"guten-TzgyWw","textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"r":7,"g":41,"b":90,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"600"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-TzgyWw">Meet With Professional Team</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-F4Bdav","alignment":{"Desktop":"center","Tablet":"center","Mobile":"center"},"textColor":{"r":113,"g":124,"b":144,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"26","left":"26"}},"Tablet":{"unit":"%","dimension":{"right":"12","left":"12"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
            <div class="guten-element gutenverse-text-editor guten-F4Bdav"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->
            
            <!-- wp:gutenverse/section {"width":"1170","isChild":true,"gap":"no","elementId":"guten-NVGsj6","margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
            <div class="section-wrapper" data-id="NVGsj6"><script>var topNVGsj6 = {"Desktop":{"point":"0","unit":"px"}};var bottomNVGsj6 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-NVGsj6 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-TBZHjG","margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-TBZHjG"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="TBZHjG"><script>var topTBZHjG = {"Desktop":{"point":"0","unit":"px"}};var bottomTBZHjG = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-9Ut7wr","profileType":"overlay","overlayType":"scale","overlayPosition":"bottom","src":{"id":134,"image":"' . esc_url( STARTUPZY_URI ) . 'assets/img/business-team-executive-group-work-job-1573331-pxhere.com.webp"},"name":"Jennifer Doe","job":"Marketing","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"22","unit":"px"}},"weight":"600"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"descColor":{"r":255,"g":255,"b":255,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"50","left":"0"}},"Tablet":[],"Mobile":[]},"profileBorder":{"radius":{"Desktop":[]}},"imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"r":2,"g":19,"b":45,"a":0.9},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"},"descSpace":{"Desktop":""},"hoverContentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-9Ut7wr"><div class="profile-box"><div class="profile-card card-overlay scale"><img src="' . esc_url( STARTUPZY_URI ) . 'assets/img/business-team-executive-group-work-job-1573331-pxhere.com.webp" alt="Jennifer Doe"/><div class="profile-body bottom"><h3 class="profile-title ">Jennifer Doe</h3><p class="profile-sub">Marketing</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-FSnYGV","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":30,"g":112,"b":234,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","left":"0","bottom":"5"}}}},"iconBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5","right":"0","left":"0"}}}},"itemPadding":{"Desktop":[]},"hoverIconColor":{"r":30,"g":112,"b":234,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":[]}} -->
            <div class="guten-element guten-social-icons guten-FSnYGV circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-ihuapy"} -->
            <div class="guten-element guten-social-icon guten-ihuapy facebook"><a id="guten-ihuapy"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-3CDTMm"} -->
            <div class="guten-element guten-social-icon guten-3CDTMm twitter"><a id="guten-3CDTMm"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-fkuBJf"} -->
            <div class="guten-element guten-social-icon guten-fkuBJf instagram"><a id="guten-fkuBJf"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-EJID1Y","margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-EJID1Y"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="EJID1Y"><script>var topEJID1Y = {"Desktop":{"point":"0","unit":"px"}};var bottomEJID1Y = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-MyOrrl","profileType":"overlay","overlayType":"scale","overlayPosition":"bottom","src":{"id":135,"image":"' . esc_url( STARTUPZY_URI ) . 'assets/img/StockSnap_UTEZRDTKPP.webp"},"name":"Jonathan Doe","job":"CEO Startupzy","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"22","unit":"px"}},"weight":"600"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"descColor":{"r":255,"g":255,"b":255,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"50","left":"0"}},"Tablet":[],"Mobile":[]},"profileBorder":{"radius":{"Desktop":[]}},"imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"r":2,"g":19,"b":45,"a":0.9},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"},"descSpace":{"Desktop":""},"hoverContentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-MyOrrl"><div class="profile-box"><div class="profile-card card-overlay scale"><img src="' . esc_url( STARTUPZY_URI ) . 'assets/img/StockSnap_UTEZRDTKPP.webp" alt="Jonathan Doe"/><div class="profile-body bottom"><h3 class="profile-title ">Jonathan Doe</h3><p class="profile-sub">CEO Startupzy</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-9jB2dJ","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":30,"g":112,"b":234,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","left":"0","bottom":"5"}}}},"iconBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5","right":"0","left":"0"}}}},"itemPadding":{"Desktop":[]},"hoverIconColor":{"r":30,"g":112,"b":234,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":[]}} -->
            <div class="guten-element guten-social-icons guten-9jB2dJ circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-bVafkf"} -->
            <div class="guten-element guten-social-icon guten-bVafkf facebook"><a id="guten-bVafkf"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-s35QKL"} -->
            <div class="guten-element guten-social-icon guten-s35QKL twitter"><a id="guten-s35QKL"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-5cVNAI"} -->
            <div class="guten-element guten-social-icon guten-5cVNAI instagram"><a id="guten-5cVNAI"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-xHFRTu","margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-xHFRTu"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="xHFRTu"><script>var topxHFRTu = {"Desktop":{"point":"0","unit":"px"}};var bottomxHFRTu = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-PWwyAs","profileType":"overlay","overlayType":"scale","overlayPosition":"bottom","src":{"id":133,"image":"' . esc_url( STARTUPZY_URI ) . 'assets/img/business-team-executive-group-work-job-1573329-pxhere.com.webp"},"name":"Christina Doe","job":"Creative Leader","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"22","unit":"px"}},"weight":"600"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"descColor":{"r":255,"g":255,"b":255,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"50","left":"0"}},"Tablet":[],"Mobile":[]},"profileBorder":{"radius":{"Desktop":[]}},"imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"r":2,"g":19,"b":45,"a":0.9},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"},"descSpace":{"Desktop":""},"hoverContentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-PWwyAs"><div class="profile-box"><div class="profile-card card-overlay scale"><img src="' . esc_url( STARTUPZY_URI ) . 'assets/img/business-team-executive-group-work-job-1573329-pxhere.com.webp" alt="Christina Doe"/><div class="profile-body bottom"><h3 class="profile-title ">Christina Doe</h3><p class="profile-sub">Creative Leader</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-B5GGdr","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":30,"g":112,"b":234,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","left":"0","bottom":"5"}}}},"iconBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5","right":"0","left":"0"}}}},"itemPadding":{"Desktop":[]},"hoverIconColor":{"r":30,"g":112,"b":234,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":[]}} -->
            <div class="guten-element guten-social-icons guten-B5GGdr circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-9I3RjG"} -->
            <div class="guten-element guten-social-icon guten-9I3RjG facebook"><a id="guten-9I3RjG"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-KoGXrf"} -->
            <div class="guten-element guten-social-icon guten-KoGXrf twitter"><a id="guten-KoGXrf"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-DVrWAG"} -->
            <div class="guten-element guten-social-icon guten-DVrWAG instagram"><a id="guten-DVrWAG"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
